name: norm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install norminette
        run: |
          git clone https://github.com/42Paris/norminette.git norminette
          cd norminette
          bundle
          mv norminette.rb ../
          cd ..
      - name: Norm
        run: ./norminette.rb ./src/*.c && ./norminette.rb ./includes/*.h