name: norm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install norminette
        run: |
          sudo apt install zsh
          zsh
          sudo apt-get install ruby ruby-bundler ruby-dev build-essential
          git clone https://github.com/42Paris/norminette.git ~/.norminette/
          cd ~/.norminette/
          bundle
          echo 'alias norminette="~/.norminette/norminette.rb"' >> ~/.zshrc
          source ~/.zshrc
      - name: Norm libft
        run: norminette ./libft/*.c && norminette ./libft/*.h 
      - name: Norm printf
        run : norminette ./src/*.c && norminette ./includes/*.h